kitchen/urls.py
from django.urls import path
from .views import (
    index,
    CookListView,
    DishListView,
    DishTypeListView,
    IngredientListView,
    CookDetailView,
    CookCreateView,
    CookExperienceUpdateView,
    CookDeleteView,
    DishDetailView,
    DishCreateView,
    DishUpdateView,
    DishDeleteView,
    DishTypeCreateView,
    DishTypeUpdateView,
    DishTypeDeleteView,
    IngredientCreateView,
    IngredientUpdateView,
    IngredientDeleteView,
)

app_name = "kitchen"

urlpatterns = [
    path("", index, name="index"),
    path("cooks/", CookListView.as_view(), name="cook-list"),
    path("cooks/<int:pk>/", CookDetailView.as_view(), name="cook-detail"),
    path("cooks/create/", CookCreateView.as_view(), name="cook-create"),
    path(
        "cooks/<int:pk>/update/",
        CookExperienceUpdateView.as_view(),
        name="cook-update"
    ),
    path(
        "cooks/<int:pk>/delete/",
        CookDeleteView.as_view(),
        name="cook-delete"
    ),
    path(
        "dishes/",
        DishListView.as_view(),
        name="dish-list"
    ),
    path(
        "dishes/<int:pk>/",
        DishDetailView.as_view(),
        name="dish-detail"
    ),
    path(
        "dishes/create/",
        DishCreateView.as_view(),
        name="dish-create"
    ),
    path(
        "dishes/<int:pk>/update/",
        DishUpdateView.as_view(),
        name="dish-update"
    ),
    path(
        "dishes/<int:pk>/delete/",
        DishDeleteView.as_view(),
        name="dish-delete"
    ),
    path(
        "dish-types/",
        DishTypeListView.as_view(),
        name="dish-type-list"
    ),
    path(
        "dish-types/create/",
        DishTypeCreateView.as_view(),
        name="dish-type-create"
    ),
    path(
        "dish-types/<int:pk>/update/",
        DishTypeUpdateView.as_view(),
        name="dish-type-update"
    ),
    path(
        "dish-types/<int:pk>/delete/",
        DishTypeDeleteView.as_view(),
        name="dish-type-delete"
    ),
    path(
        "ingredients/",
        IngredientListView.as_view(),
        name="ingredient-list"
    ),
    path(
        "ingredients/create/",
        IngredientCreateView.as_view(),
        name="ingredient-create"
    ),
    path(
        "ingredients/<int:pk>/update/",
        IngredientUpdateView.as_view(),
        name="ingredient-update"
    ),
    path(
        "ingredients/<int:pk>/delete/",
        IngredientDeleteView.as_view(),
        name="ingredient-delete"
    ),
]

kitchen_service/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("kitchen.urls", namespace="kitchen")),
    path("accounts/", include("django.contrib.auth.urls")),
]

kitchen/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.urls import reverse

from kitchen_service.settings import base


class DishType(models.Model):
    name = models.CharField(max_length=255)

    class Meta:
        ordering = ("name", )

    def __str__(self):
        return self.name


class Cook(AbstractUser):
    years_of_experience = models.IntegerField(default=0)

    class Meta:
        ordering = ("username", )

    def __str__(self):
        return f"{self.username}: ({self.first_name} {self.last_name})"

    def get_absolute_url(self):
        return reverse("kitchen:cook-detail", kwargs={"pk": self.pk})


class Ingredient(models.Model):
    name = models.CharField(max_length=63)

    class Meta:
        ordering = ("name", )

    def __str__(self):
        return self.name


class Dish(models.Model):
    name = models.CharField(max_length=255)
    description = models.TextField()
    price = models.DecimalField(max_digits=10, decimal_places=2)
    type = models.ForeignKey(
        DishType,
        on_delete=models.CASCADE,
        related_name="dishes"
    )
    cooks = models.ManyToManyField(
        base.AUTH_USER_MODEL,
        related_name="dishes"
    )
    ingredients = models.ManyToManyField(Ingredient, related_name="dishes")

    class Meta:
        ordering = ("name", )
        verbose_name_plural = "dishes"

    def __str__(self):
        return f"{self.name} (price: {self.price}, type: {self.type})"

kitchen/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm

from kitchen.models import Dish, Cook, Ingredient


class DishForm(forms.ModelForm):
    cooks = forms.ModelMultipleChoiceField(
        queryset=get_user_model().objects.all(),
        widget=forms.CheckboxSelectMultiple,
    )
    ingredients = forms.ModelMultipleChoiceField(
        queryset=Ingredient.objects.all(),
        widget=forms.CheckboxSelectMultiple,
    )

    class Meta:
        model = Dish
        fields = "__all__"


class DishSearchForm(forms.Form):
    name = forms.CharField(
        max_length=255,
        required=False,
        label="",
        widget=forms.TextInput(
            attrs={
                "placeholder": "Search by name"
            }
        )
    )


class CookCreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = Cook
        fields = UserCreationForm.Meta.fields + (
            "first_name",
            "last_name",
            "years_of_experience",
        )


class CookSearchForm(forms.Form):
    username = forms.CharField(
        max_length=255,
        required=False,
        label="",
        widget=forms.TextInput(
            attrs={
                "placeholder": "Search by username"
            }
        )
    )


class CookExperienceUpdateForm(forms.ModelForm):
    class Meta:
        model = Cook
        fields = ["years_of_experience", ]


class DishTypeSearchForm(forms.Form):
    name = forms.CharField(
        max_length=255,
        required=False,
        label="",
        widget=forms.TextInput(
            attrs={
                "placeholder": "Search by name"
            }
        )
    )


class IngredientSearchForm(forms.Form):
    name = forms.CharField(
        max_length=255,
        required=False,
        label="",
        widget=forms.TextInput(
            attrs={
                "placeholder": "Search by name"
            }
        )
    )

kitchen/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views import generic

from kitchen.forms import (
    DishForm,
    CookCreationForm,
    CookExperienceUpdateForm,
    DishTypeSearchForm,
    CookSearchForm,
    DishSearchForm, IngredientSearchForm,
)
from kitchen.models import Cook, Dish, DishType, Ingredient


def index(request):
    """View function for the home page of site."""
    num_cooks = Cook.objects.count()
    num_dishes = Dish.objects.count()
    num_dish_types = DishType.objects.count()
    num_ingredients = Ingredient.objects.count()
    context = {
        "num_cooks": num_cooks,
        "num_dishes": num_dishes,
        "num_dish_types": num_dish_types,
        "num_ingredients": num_ingredients
    }
    return render(request, "kitchen/index.html", context=context)


class DishTypeListView(LoginRequiredMixin, generic.ListView):
    model = DishType
    context_object_name = "dish_type_list"
    template_name = "kitchen/dish_type_list.html"
    paginate_by = 10

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(DishTypeListView, self).get_context_data(**kwargs)
        name = self.request.GET.get("name", "")
        context["search_form"] = DishTypeSearchForm(initial={"name": name})
        return context

    def get_queryset(self):
        queryset = DishType.objects.all()
        form = DishTypeSearchForm(self.request.GET)

        if form.is_valid():
            return queryset.filter(name__icontains=form.cleaned_data["name"])
        return queryset


class DishTypeCreateView(LoginRequiredMixin, generic.CreateView):
    model = DishType
    fields = "__all__"
    template_name = "kitchen/dish_type_form.html"
    success_url = reverse_lazy("kitchen:dish-type-list")
    context_object_name = "dish_type"


class DishTypeUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = DishType
    fields = "__all__"
    template_name = "kitchen/dish_type_form.html"
    success_url = reverse_lazy("kitchen:dish-type-list")
    context_object_name = "dish_type"


class DishTypeDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = DishType
    template_name = "kitchen/dish_type_confirm_delete.html"
    success_url = reverse_lazy("kitchen:dish-type-list")
    context_object_name = "dish_type"


class DishListView(LoginRequiredMixin, generic.ListView):
    model = Dish
    paginate_by = 10

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(DishListView, self).get_context_data(**kwargs)
        name = self.request.GET.get("name", "")
        context["search_form"] = DishSearchForm(initial={"name": name})
        return context

    def get_queryset(self):
        queryset = Dish.objects.select_related("type")
        form = DishSearchForm(self.request.GET)

        if form.is_valid():
            return queryset.filter(name__icontains=form.cleaned_data["name"])
        return queryset


class DishDetailView(LoginRequiredMixin, generic.DetailView):
    model = Dish


class DishCreateView(LoginRequiredMixin, generic.CreateView):
    model = Dish
    form_class = DishForm
    success_url = reverse_lazy("kitchen:dish-list")


class DishUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Dish
    form_class = DishForm
    success_url = reverse_lazy("kitchen:dish-list")


class DishDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Dish
    success_url = reverse_lazy("kitchen:dish-list")


class CookListView(LoginRequiredMixin, generic.ListView):
    model = Cook
    paginate_by = 10

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(CookListView, self).get_context_data(**kwargs)
        username = self.request.GET.get("username", "")
        context["search_form"] = CookSearchForm(initial={"username": username})
        return context

    def get_queryset(self):
        queryset = Cook.objects.all()
        form = CookSearchForm(self.request.GET)

        if form.is_valid():
            return queryset.filter(
                username__icontains=form.cleaned_data["username"]
            )
        return queryset


class CookDetailView(LoginRequiredMixin, generic.DetailView):
    model = Cook
    queryset = Cook.objects.prefetch_related("dishes__type")


class CookCreateView(LoginRequiredMixin, generic.CreateView):
    model = Cook
    template_name = "kitchen/cook_form.html"
    form_class = CookCreationForm


class CookExperienceUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Cook
    form_class = CookExperienceUpdateForm
    template_name = "kitchen/cook_form.html"
    success_url = reverse_lazy("kitchen:cook-list")


class CookDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Cook
    success_url = reverse_lazy("kitchen:cook-list")


class IngredientListView(LoginRequiredMixin, generic.ListView):
    model = Ingredient
    template_name = "kitchen/ingredient_list.html"
    paginate_by = 10

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(IngredientListView, self).get_context_data(**kwargs)
        name = self.request.GET.get("name", "")
        context["search_form"] = IngredientSearchForm(initial={"name": name})
        return context

    def get_queryset(self):
        queryset = Ingredient.objects.all()
        form = IngredientSearchForm(self.request.GET)
        if form.is_valid():
            return queryset.filter(name__icontains=form.cleaned_data["name"])
        return queryset


class IngredientCreateView(LoginRequiredMixin, generic.CreateView):
    model = Ingredient
    fields = "__all__"
    success_url = reverse_lazy("kitchen:ingredient-list")


class IngredientUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Ingredient
    fields = "__all__"
    success_url = reverse_lazy("kitchen:ingredient-list")


class IngredientDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Ingredient
    template_name = "kitchen/ingredient_confirm_delete.html"
    success_url = reverse_lazy("kitchen:ingredient-list")

templates/kitchen/cook_detail.html
{% extends "layouts/base-presentation.html" %}
{% load crispy_forms_filters %}

{% block title %} Cook {% endblock title %}

{% block navigation %}
  {% include "includes/navigation.html" %}
{% endblock %}
{% block content %}
  <header class="header-2">
    <div class="page-header section-height-50 relative"
         style="background-image: url('{{ ASSETS_ROOT }}/img/cook-list2.jpg')">
      <div class="position-absolute w-100 z-index-1 bottom-0">
        <svg class="waves" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"
             viewBox="0 24 150 40" preserveAspectRatio="none" shape-rendering="auto">
          <defs>
            <path id="gentle-wave" d="M-160 44c30 0 58-18 88-18s 58 18 88 18 58-18 88-18 58 18 88 18 v44h-352z"/>
          </defs>
          <g class="moving-waves">
            <use xlink:href="#gentle-wave" x="48" y="-1" fill="rgba(255,255,255,0.40"/>
            <use xlink:href="#gentle-wave" x="48" y="3" fill="rgba(255,255,255,0.35)"/>
            <use xlink:href="#gentle-wave" x="48" y="5" fill="rgba(255,255,255,0.25)"/>
            <use xlink:href="#gentle-wave" x="48" y="8" fill="rgba(255,255,255,0.20)"/>
            <use xlink:href="#gentle-wave" x="48" y="13" fill="rgba(255,255,255,0.15)"/>
            <use xlink:href="#gentle-wave" x="48" y="16" fill="rgba(255,255,255,0.95"/>
          </g>
        </svg>
      </div>
    </div>
  </header>
  <section class="pt-2 pb-5" id="count-stats">
    <div class="container">
      <div class="row">
        <div class="z-index-2 border-radius-xl mt-n12 mx-auto py-3 blur shadow-blur">
          <div class="row p-2">
            <div class="position-relative col-md-9">
              <div class="m-0 text-lighter mt-n2">
                <h1>
                  Username: {{ cook.username }}
                </h1>
              </div>
            </div>
            <div class="position-relative col-md-1 ms-6">
              <a href="{% url 'kitchen:cook-update' pk=cook.id %}"
                 class="btn btn-outline-secondary btn-round link-to-page mb-md-1">
                Update
              </a>
            </div>
            <div class="position-relative col-md-1">
              <a href="{% url 'kitchen:cook-delete' pk=cook.id %}"
                 class="btn btn-outline-warning btn-round link-to-page mb-md-1">
                Delete
              </a>
            </div>
          </div>
          <div class="row">
            <div class="position-relative">
              <div class="m-4 text-dark">
                <p><strong>First name:</strong> {{ cook.first_name }}</p>
                <p><strong>Last name:</strong> {{ cook.last_name }}</p>
                <p><strong>Years of experience:</strong> {{ cook.years_of_experience }}</p>
                <p><strong>Is staff:</strong> {{ cook.is_staff }}</p>
              </div>
            </div>
          </div>
          <div class="row">
            <div class="position-relative">
              <div class="m-6 text-lighter">
                <h4>Dishes</h4>
                {% for dish in cook.dishes.all %}
                  <hr>
                  <p><strong>Name:</strong> {{ dish.name }}</p>
                  <p><strong>Dish type:</strong> {{ dish.type.name }}</p>
                  <p class="text-muted"><strong>Id:</strong> {{ dish.id }}</p>
                {% empty %}
                  <p>No dishes!</p>
                {% endfor %}
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
{% endblock %}

templates/kitchen/dish_detail.html
{% extends "layouts/base-presentation.html" %}
{% load crispy_forms_filters %}

{% block title %} Dish {% endblock title %}

{% block navigation %}
  {% include "includes/navigation.html" %}
{% endblock %}
{% block content %}
  <header class="header-2">
    <div class="page-header section-height-50 relative"
         style="background-image: url('{{ ASSETS_ROOT }}/img/dish-list.jpg')">
      <div class="position-absolute w-100 z-index-1 bottom-0">
        <svg class="waves" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"
             viewBox="0 24 150 40" preserveAspectRatio="none" shape-rendering="auto">
          <defs>
            <path id="gentle-wave" d="M-160 44c30 0 58-18 88-18s 58 18 88 18 58-18 88-18 58 18 88 18 v44h-352z"/>
          </defs>
          <g class="moving-waves">
            <use xlink:href="#gentle-wave" x="48" y="-1" fill="rgba(255,255,255,0.40"/>
            <use xlink:href="#gentle-wave" x="48" y="3" fill="rgba(255,255,255,0.35)"/>
            <use xlink:href="#gentle-wave" x="48" y="5" fill="rgba(255,255,255,0.25)"/>
            <use xlink:href="#gentle-wave" x="48" y="8" fill="rgba(255,255,255,0.20)"/>
            <use xlink:href="#gentle-wave" x="48" y="13" fill="rgba(255,255,255,0.15)"/>
            <use xlink:href="#gentle-wave" x="48" y="16" fill="rgba(255,255,255,0.95"/>
          </g>
        </svg>
      </div>
    </div>
  </header>
  <section class="pt-2 pb-5" id="count-stats">
    <div class="container">
      <div class="row">
        <div class="z-index-2 border-radius-xl mt-n12 mx-auto py-3 blur shadow-blur">
          <div class="row p-2">
            <div class="position-relative col-md-9">
              <div class="m-0 text-lighter mt-n2">
                <h1>
                  {{ dish.name }}
                </h1>
              </div>
            </div>
            <div class="position-relative col-md-1 ms-6">
              <a href="{% url 'kitchen:dish-update' pk=dish.id %}"
                 class="btn btn-outline-secondary btn-round link-to-page mb-md-1">
                Update
              </a>
            </div>
            <div class="position-relative col-md-1">
              <a href="{% url 'kitchen:dish-delete' pk=dish.id %}"
                 class="btn btn-outline-warning btn-round link-to-page mb-md-1">
                Delete
              </a>
            </div>
          </div>
          <div class="row">
            <div class="position-relative">
              <div class="ms-4 text-dark">
                <p><strong>Dish type:</strong> {{ dish.type.name }}</p>
                <p><strong>Description:</strong> {{ dish.description }}</p>
              </div>
            </div>
          </div>
          <div class="row">
            <div class="position-relative col-md-6">
              <div class="ms-6 text-lighter">
                <h4>Ingredients</h4>
                <hr>
                <ul>
                  {% for ingredient in dish.ingredients.all %}
                    <li>{{ ingredient.name }}</li>
                  {% endfor %}
                </ul>
              </div>
            </div>
            <div class="position-relative col-md-6">
              <div class="ms-6 text-lighter">
                <h4>Cooks</h4>
                <hr>
                <ul>
                  {% for cook in dish.cooks.all %}
                    <li>{{ cook.username }} ({{ cook.first_name }} {{ cook.last_name }})</li>
                  {% endfor %}
                </ul>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
{% endblock %}

templates/kitchen/dish_type_list.html
{% extends "layouts/base-presentation.html" %}
{% load crispy_forms_filters %}

{% block title %} Dish Types {% endblock title %}

{% block navigation %}
  {% include "includes/navigation.html" %}
{% endblock %}
{% block content %}
  <header class="header-2">
    <div class="page-header section-height-50 relative"
         style="background-image: url('{{ ASSETS_ROOT }}/img/dish-type-list-1.jpg')">
      <div class="position-absolute w-100 z-index-1 bottom-0">
        <svg class="waves" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"
             viewBox="0 24 150 40" preserveAspectRatio="none" shape-rendering="auto">
          <defs>
            <path id="gentle-wave" d="M-160 44c30 0 58-18 88-18s 58 18 88 18 58-18 88-18 58 18 88 18 v44h-352z"/>
          </defs>
          <g class="moving-waves">
            <use xlink:href="#gentle-wave" x="48" y="-1" fill="rgba(255,255,255,0.40"/>
            <use xlink:href="#gentle-wave" x="48" y="3" fill="rgba(255,255,255,0.35)"/>
            <use xlink:href="#gentle-wave" x="48" y="5" fill="rgba(255,255,255,0.25)"/>
            <use xlink:href="#gentle-wave" x="48" y="8" fill="rgba(255,255,255,0.20)"/>
            <use xlink:href="#gentle-wave" x="48" y="13" fill="rgba(255,255,255,0.15)"/>
            <use xlink:href="#gentle-wave" x="48" y="16" fill="rgba(255,255,255,0.95"/>
          </g>
        </svg>
      </div>
    </div>
  </header>
  <section class="pt-2 pb-5" id="count-stats">
    <div class="container">
      <div class="row">
        <div class="z-index-2 border-radius-xl mt-n12 mx-auto py-3 blur shadow-blur">
          <div class="row">
            <div class="position-relative col-md-3">
              <div class="pt-1 m-0 text-left">
                <h1 class="text-lighter text-center mt-n3">
                  Dish Types
                </h1>
              </div>
            </div>
            <div class="position-relative col-md-8 p-0">
              <form action="" method="get">
                {{ search_form|crispy }}
              </form>
            </div>
            <div class="position-relative col-md-auto ms-auto me-3 p-0">
              <div class="text-left">
                <a href="{% url 'kitchen:dish-type-create' %}" style="float: right;"
                   class="btn btn-round bg-gradient-dark link-to-page">+</a>
              </div>
            </div>
            <div class="position-relative">
              {% if dish_type_list %}
                <table class="table">
                  <tr>
                    <th class="col-md-2">ID</th>
                    <th class="col-md-5">Name</th>
                    <th class="col-md-3">Update</th>
                    <th class="col-md-auto">Delete</th>
                  </tr>
                  {% for dish_type in dish_type_list %}
                    <tr>
                      <td>
                        {{ dish_type.id }}
                      </td>
                      <td class="text-gradient text-dark">
                        <strong>{{ dish_type.name }}</strong>
                      </td>
                      <td>
                        <a class="btn btn-sm btn-outline-secondary btn-round mb-md-1"
                           href="{% url 'kitchen:dish-type-update' pk=dish_type.id %}">UPDATE</a>
                      </td>
                      <td>
                        <a class="btn btn-sm btn-outline-warning btn-round mb-md-1"
                           href="{% url 'kitchen:dish-type-delete' pk=dish_type.id %}">DELETE</a>
                      </td>
                    </tr>
                  {% endfor %}
                </table>
              {% else %}
                <p>There are no Dish Types</p>
              {% endif %}
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
{% endblock %}

templates/kitchen/ingredient_list.html
{% extends "layouts/base-presentation.html" %}
{% load crispy_forms_filters %}

{% block title %} Ingredients {% endblock title %}

{% block navigation %}
  {% include "includes/navigation.html" %}
{% endblock %}
{% block content %}
  <header class="header-2">
    <div class="page-header section-height-50 relative"
         style="background-image: url('{{ ASSETS_ROOT }}/img/ingredient-list-1.jpg')">
      <div class="position-absolute w-100 z-index-1 bottom-0">
        <svg class="waves" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"
             viewBox="0 24 150 40" preserveAspectRatio="none" shape-rendering="auto">
          <defs>
            <path id="gentle-wave" d="M-160 44c30 0 58-18 88-18s 58 18 88 18 58-18 88-18 58 18 88 18 v44h-352z"/>
          </defs>
          <g class="moving-waves">
            <use xlink:href="#gentle-wave" x="48" y="-1" fill="rgba(255,255,255,0.40"/>
            <use xlink:href="#gentle-wave" x="48" y="3" fill="rgba(255,255,255,0.35)"/>
            <use xlink:href="#gentle-wave" x="48" y="5" fill="rgba(255,255,255,0.25)"/>
            <use xlink:href="#gentle-wave" x="48" y="8" fill="rgba(255,255,255,0.20)"/>
            <use xlink:href="#gentle-wave" x="48" y="13" fill="rgba(255,255,255,0.15)"/>
            <use xlink:href="#gentle-wave" x="48" y="16" fill="rgba(255,255,255,0.95"/>
          </g>
        </svg>
      </div>
    </div>
  </header>
  <section class="pt-2 pb-5" id="count-stats">
    <div class="container">
      <div class="row">
        <div class="z-index-2 border-radius-xl mt-n12 mx-auto py-3 blur shadow-blur">
          <div class="row">
            <div class="position-relative col-md-3">
              <div class="pt-1 text-center text-left">
                <h1 class="text-lighter mt-n3">
                  Ingredients
                </h1>
              </div>
            </div>

            <div class="position-relative col-md-8 p-0">
              <form action="" method="get" class="d-inline m-0">
                {{ search_form|crispy }}
              </form>
            </div>
            <div class="position-relative col-md-auto ms-auto me-3 p-0">
              <div class="text-left">
                <a href="{% url 'kitchen:ingredient-create' %}" style="float: right;"
                   class="btn btn-round bg-gradient-dark link-to-page">+</a>
              </div>
            </div>
          </div>
          <div class="row">
            <div class="position-relative">
              {% if ingredient_list %}
                <table class="table">
                  <tr>
                    <th class="col-md-2">ID</th>
                    <th class="col-md-5">Name</th>
                    <th class="col-md-3">Update</th>
                    <th class="col-md-auto">Delete</th>
                  </tr>
                  {% for ingredient in ingredient_list %}
                    <tr>
                      <td>
                        {{ ingredient.id }}
                      </td>
                      <td class="text-gradient text-dark">
                        <strong>{{ ingredient.name }}</strong>
                      </td>
                      <td>
                        <a class="btn btn-sm btn-outline-secondary btn-round mb-md-1"
                           href="{% url 'kitchen:ingredient-update' pk=ingredient.id %}">UPDATE</a>
                      </td>
                      <td>
                        <a class="btn btn-sm btn-outline-warning btn-round mb-md-1"
                           href="{% url 'kitchen:ingredient-delete' pk=ingredient.id %}">DELETE</a>
                      </td>
                    </tr>
                  {% endfor %}
                </table>
              {% else %}
                <p>There are no Ingredients.</p>
              {% endif %}
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
{% endblock %}